name: Check Markdown links
on:
  push:

jobs:
  markdown-link-check:
    name: Markdown Link Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: .github/workflows/markdown-link-check.json
          use-quiet-mode: 'no'
          use-verbose-mode: 'yes'
